var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/type-unites-organisationnelles/route.js")
R.c("server/chunks/[root-of-the-server]__c22d296a._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_28bf31c1.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/ce889_server_app_api_type-unites-organisationnelles_route_actions_a52f894b.js")
R.m(595709)
module.exports=R.m(595709).exports
