var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/agent/role-permission/bootstrap/route.js")
R.c("server/chunks/[root-of-the-server]__577502c2._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_88980151.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/ce889_server_app_api_agent_role-permission_bootstrap_route_actions_b3153884.js")
R.m(818721)
module.exports=R.m(818721).exports
