var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/affectations/route.js")
R.c("server/chunks/[root-of-the-server]__6db2cfbf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_6f0ecaba.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/_next-internal_server_app_api_affectations_route_actions_0c22381c.js")
R.m(924624)
module.exports=R.m(924624).exports
