var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/polyclinique/demandes/[id]/dossier/route.js")
R.c("server/chunks/[root-of-the-server]__6021972b._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/ce889_server_app_api_polyclinique_demandes_[id]_dossier_route_actions_d3e750a0.js")
R.m(156206)
module.exports=R.m(156206).exports
