var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/utilisateur/utilisateur-role/route.js")
R.c("server/chunks/[root-of-the-server]__203b8af4._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/ce889_server_app_api_utilisateur_utilisateur-role_route_actions_af6f7829.js")
R.m(915058)
module.exports=R.m(915058).exports
