var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/biometrie/pointer/route.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/[root-of-the-server]__a0be0ea1._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/_next-internal_server_app_api_biometrie_pointer_route_actions_afa9fe47.js")
R.m(583765)
module.exports=R.m(583765).exports
