var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/agent/conge/demande/all/route.js")
R.c("server/chunks/[root-of-the-server]__c967c76b._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/_next-internal_server_app_api_agent_conge_demande_all_route_actions_a04a6919.js")
R.m(846037)
module.exports=R.m(846037).exports
