var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/type-planifications/route.js")
R.c("server/chunks/[root-of-the-server]__ea92a58d._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/_next-internal_server_app_api_type-planifications_route_actions_d23906db.js")
R.m(414465)
module.exports=R.m(414465).exports
