var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/agent/resetPassword/route.js")
R.c("server/chunks/[root-of-the-server]__cb3431d8._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_bcryptjs_index_42ebb250.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/_next-internal_server_app_api_agent_resetPassword_route_actions_5162d04f.js")
R.m(936886)
module.exports=R.m(936886).exports
