export const POLYCLINIQUE_PERMISSION = {
  ACCESS: "polyclinique.access",
  DEMANDE_READ: "polyclinique_demande.read",
  DEMANDE_REQUEST: "polyclinique_demande.request",
  DEMANDE_VALIDATE: "polyclinique_demande.validate",
  DOSSIER_READ: "polyclinique_dossier.read",
  DOSSIER_CREATE: "polyclinique_dossier.create",
} as const;

export const POLYCLINIQUE_ACCESS_CODES = [
  POLYCLINIQUE_PERMISSION.ACCESS,
  POLYCLINIQUE_PERMISSION.DEMANDE_READ,
  POLYCLINIQUE_PERMISSION.DEMANDE_REQUEST,
  POLYCLINIQUE_PERMISSION.DEMANDE_VALIDATE,
  POLYCLINIQUE_PERMISSION.DOSSIER_READ,
  POLYCLINIQUE_PERMISSION.DOSSIER_CREATE,
] as const;

export const POLYCLINIQUE_SCOPE_CODES = [
  POLYCLINIQUE_PERMISSION.DEMANDE_READ,
  POLYCLINIQUE_PERMISSION.DEMANDE_REQUEST,
  POLYCLINIQUE_PERMISSION.DEMANDE_VALIDATE,
  POLYCLINIQUE_PERMISSION.DOSSIER_READ,
  POLYCLINIQUE_PERMISSION.DOSSIER_CREATE,
] as const;
