// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/access" | "/dashboard/agents" | "/dashboard/agents/[id]" | "/dashboard/carrieres" | "/dashboard/conges" | "/dashboard/dossier-agent" | "/dashboard/organisation" | "/dashboard/paie" | "/dashboard/parametre/notifications" | "/dashboard/parametre/session" | "/dashboard/planification" | "/dashboard/polyclinique" | "/dashboard/presenceAbsence" | "/dashboard/tabord" | "/forgot" | "/login" | "/passreset" | "/pointage/biometrique"
type AppRouteHandlerRoutes = "/api/affectations" | "/api/affectations/historique" | "/api/affectations/validation" | "/api/agent" | "/api/agent/agUserCompteNumber" | "/api/agent/agentWithAccount" | "/api/agent/compte-utilisateur" | "/api/agent/conge" | "/api/agent/conge/demande" | "/api/agent/conge/demande/all" | "/api/agent/dash" | "/api/agent/dash/dashAdmin" | "/api/agent/forgotPassword" | "/api/agent/historique-agent" | "/api/agent/horaireAgent" | "/api/agent/horaireTravail" | "/api/agent/parcours/[agentId]" | "/api/agent/permission" | "/api/agent/permission/bootstrap" | "/api/agent/photo" | "/api/agent/presence" | "/api/agent/presence/admin" | "/api/agent/presence/pointages" | "/api/agent/presence/today" | "/api/agent/resetPassword" | "/api/agent/role" | "/api/agent/role-permission" | "/api/agent/role-permission/bootstrap" | "/api/auth/login" | "/api/auth/logout" | "/api/biometrie/pointer" | "/api/biometrie/references" | "/api/biometrie/referentiels" | "/api/carrieres" | "/api/carrieres/agents" | "/api/carrieres/retraite/proche" | "/api/fonctions" | "/api/grades" | "/api/notification" | "/api/paie" | "/api/paie/getPaiesByAgent" | "/api/paie/prime" | "/api/planifications" | "/api/polyclinique/dashboard" | "/api/polyclinique/demandes" | "/api/polyclinique/demandes/[id]/dossier" | "/api/polyclinique/demandes/[id]/validation" | "/api/postes" | "/api/provinces" | "/api/session" | "/api/session/heartbeat" | "/api/type-planifications" | "/api/type-unites-organisationnelles" | "/api/unites-organisationnelles" | "/api/utilisateur" | "/api/utilisateur/utilisateur-role"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/affectations": {}
  "/api/affectations/historique": {}
  "/api/affectations/validation": {}
  "/api/agent": {}
  "/api/agent/agentWithAccount": {}
  "/api/agent/agUserCompteNumber": {}
  "/api/agent/compte-utilisateur": {}
  "/api/agent/conge": {}
  "/api/agent/conge/demande": {}
  "/api/agent/conge/demande/all": {}
  "/api/agent/dash": {}
  "/api/agent/dash/dashAdmin": {}
  "/api/agent/forgotPassword": {}
  "/api/agent/historique-agent": {}
  "/api/agent/horaireAgent": {}
  "/api/agent/horaireTravail": {}
  "/api/agent/parcours/[agentId]": { "agentId": string; }
  "/api/agent/permission": {}
  "/api/agent/permission/bootstrap": {}
  "/api/agent/photo": {}
  "/api/agent/presence": {}
  "/api/agent/presence/admin": {}
  "/api/agent/presence/pointages": {}
  "/api/agent/presence/today": {}
  "/api/agent/resetPassword": {}
  "/api/agent/role": {}
  "/api/agent/role-permission": {}
  "/api/agent/role-permission/bootstrap": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/biometrie/pointer": {}
  "/api/biometrie/references": {}
  "/api/biometrie/referentiels": {}
  "/api/carrieres": {}
  "/api/carrieres/agents": {}
  "/api/carrieres/retraite/proche": {}
  "/api/fonctions": {}
  "/api/grades": {}
  "/api/notification": {}
  "/api/paie": {}
  "/api/paie/getPaiesByAgent": {}
  "/api/paie/prime": {}
  "/api/planifications": {}
  "/api/polyclinique/dashboard": {}
  "/api/polyclinique/demandes": {}
  "/api/polyclinique/demandes/[id]/dossier": { "id": string; }
  "/api/polyclinique/demandes/[id]/validation": { "id": string; }
  "/api/postes": {}
  "/api/provinces": {}
  "/api/session": {}
  "/api/session/heartbeat": {}
  "/api/type-planifications": {}
  "/api/type-unites-organisationnelles": {}
  "/api/unites-organisationnelles": {}
  "/api/utilisateur": {}
  "/api/utilisateur/utilisateur-role": {}
  "/dashboard": {}
  "/dashboard/access": {}
  "/dashboard/agents": {}
  "/dashboard/agents/[id]": { "id": string; }
  "/dashboard/carrieres": {}
  "/dashboard/conges": {}
  "/dashboard/dossier-agent": {}
  "/dashboard/organisation": {}
  "/dashboard/paie": {}
  "/dashboard/parametre/notifications": {}
  "/dashboard/parametre/session": {}
  "/dashboard/planification": {}
  "/dashboard/polyclinique": {}
  "/dashboard/presenceAbsence": {}
  "/dashboard/tabord": {}
  "/forgot": {}
  "/login": {}
  "/passreset": {}
  "/pointage/biometrique": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
