// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(page)/forgot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot">> = Specific
  const handler = {} as typeof import("../../src/app/(page)/forgot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(page)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(page)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(page)/passreset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/passreset">> = Specific
  const handler = {} as typeof import("../../src/app/(page)/passreset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/access">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/agents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/agents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agents">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/carrieres/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/carrieres">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/carrieres/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/conges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/conges">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/conges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/dossier-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/dossier-agent">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/dossier-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/organisation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/organisation">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/organisation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/paie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/paie">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/paie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parametre/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parametre/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parametre/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/parametre/session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/parametre/session">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/parametre/session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/planification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/planification">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/planification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/polyclinique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/polyclinique">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/polyclinique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/presenceAbsence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/presenceAbsence">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/presenceAbsence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/tabord/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tabord">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/tabord/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pointage/biometrique/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pointage/biometrique">> = Specific
  const handler = {} as typeof import("../../src/app/pointage/biometrique/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affectations/historique/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affectations/historique">> = Specific
  const handler = {} as typeof import("../../src/app/api/affectations/historique/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affectations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affectations">> = Specific
  const handler = {} as typeof import("../../src/app/api/affectations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/affectations/validation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/affectations/validation">> = Specific
  const handler = {} as typeof import("../../src/app/api/affectations/validation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/agUserCompteNumber/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/agUserCompteNumber">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/agUserCompteNumber/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/agentWithAccount/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/agentWithAccount">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/agentWithAccount/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/compte-utilisateur/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/compte-utilisateur">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/compte-utilisateur/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/conge/demande/all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/conge/demande/all">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/conge/demande/all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/conge/demande/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/conge/demande">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/conge/demande/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/conge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/conge">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/conge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/dash/dashAdmin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/dash/dashAdmin">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/dash/dashAdmin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/dash/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/dash">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/dash/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/forgotPassword/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/forgotPassword">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/forgotPassword/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/historique-agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/historique-agent">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/historique-agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/horaireAgent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/horaireAgent">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/horaireAgent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/horaireTravail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/horaireTravail">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/horaireTravail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/parcours/[agentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/parcours/[agentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/parcours/[agentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/permission/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/permission/bootstrap">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/permission/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/permission/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/permission">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/permission/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/presence/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/presence/admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/presence/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/presence/pointages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/presence/pointages">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/presence/pointages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/presence">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/presence/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/presence/today">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/presence/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/resetPassword/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/resetPassword">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/resetPassword/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/role-permission/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/role-permission/bootstrap">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/role-permission/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/role-permission/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/role-permission">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/role-permission/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/role">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent">> = Specific
  const handler = {} as typeof import("../../src/app/api/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/biometrie/pointer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/biometrie/pointer">> = Specific
  const handler = {} as typeof import("../../src/app/api/biometrie/pointer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/biometrie/references/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/biometrie/references">> = Specific
  const handler = {} as typeof import("../../src/app/api/biometrie/references/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/biometrie/referentiels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/biometrie/referentiels">> = Specific
  const handler = {} as typeof import("../../src/app/api/biometrie/referentiels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/carrieres/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/carrieres/agents">> = Specific
  const handler = {} as typeof import("../../src/app/api/carrieres/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/carrieres/retraite/proche/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/carrieres/retraite/proche">> = Specific
  const handler = {} as typeof import("../../src/app/api/carrieres/retraite/proche/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/carrieres/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/carrieres">> = Specific
  const handler = {} as typeof import("../../src/app/api/carrieres/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fonctions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fonctions">> = Specific
  const handler = {} as typeof import("../../src/app/api/fonctions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/grades/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/grades">> = Specific
  const handler = {} as typeof import("../../src/app/api/grades/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notification">> = Specific
  const handler = {} as typeof import("../../src/app/api/notification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/paie/getPaiesByAgent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paie/getPaiesByAgent">> = Specific
  const handler = {} as typeof import("../../src/app/api/paie/getPaiesByAgent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/paie/prime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paie/prime">> = Specific
  const handler = {} as typeof import("../../src/app/api/paie/prime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/paie/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paie">> = Specific
  const handler = {} as typeof import("../../src/app/api/paie/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/planifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/planifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/planifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/polyclinique/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/polyclinique/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/polyclinique/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/polyclinique/demandes/[id]/dossier/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/polyclinique/demandes/[id]/dossier">> = Specific
  const handler = {} as typeof import("../../src/app/api/polyclinique/demandes/[id]/dossier/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/polyclinique/demandes/[id]/validation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/polyclinique/demandes/[id]/validation">> = Specific
  const handler = {} as typeof import("../../src/app/api/polyclinique/demandes/[id]/validation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/polyclinique/demandes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/polyclinique/demandes">> = Specific
  const handler = {} as typeof import("../../src/app/api/polyclinique/demandes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/postes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/postes">> = Specific
  const handler = {} as typeof import("../../src/app/api/postes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provinces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provinces">> = Specific
  const handler = {} as typeof import("../../src/app/api/provinces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/session/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/heartbeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/session/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/type-planifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/type-planifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/type-planifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/type-unites-organisationnelles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/type-unites-organisationnelles">> = Specific
  const handler = {} as typeof import("../../src/app/api/type-unites-organisationnelles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/unites-organisationnelles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unites-organisationnelles">> = Specific
  const handler = {} as typeof import("../../src/app/api/unites-organisationnelles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/utilisateur/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/utilisateur">> = Specific
  const handler = {} as typeof import("../../src/app/api/utilisateur/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/utilisateur/utilisateur-role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/utilisateur/utilisateur-role">> = Specific
  const handler = {} as typeof import("../../src/app/api/utilisateur/utilisateur-role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
