var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/biometrie/references/route.js")
R.c("server/chunks/[root-of-the-server]__56342e30._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/_next-internal_server_app_api_biometrie_references_route_actions_f816f4ea.js")
R.m(112313)
module.exports=R.m(112313).exports
