var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/planifications/route.js")
R.c("server/chunks/[root-of-the-server]__6db2cfbf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_947c7b0c.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/_next-internal_server_app_api_planifications_route_actions_0f0ab204.js")
R.m(662479)
module.exports=R.m(662479).exports
