var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/unites-organisationnelles/route.js")
R.c("server/chunks/[root-of-the-server]__c22d296a._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_b10688e3.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/_next-internal_server_app_api_unites-organisationnelles_route_actions_f78bb2e2.js")
R.m(394992)
module.exports=R.m(394992).exports
