var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/agent/presence/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_6d45a903.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__b2f55b93._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/_next-internal_server_app_api_agent_presence_route_actions_abb4fde7.js")
R.m(721918)
module.exports=R.m(721918).exports
