var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/paie/getPaiesByAgent/route.js")
R.c("server/chunks/[root-of-the-server]__2645a7fd._.js")
R.c("server/chunks/node_modules_3704b130._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/[root-of-the-server]__00b89f99._.js")
R.c("server/chunks/[root-of-the-server]__d7355d04._.js")
R.c("server/chunks/node_modules_next_dist_79f1aee4._.js")
R.c("server/chunks/_next-internal_server_app_api_paie_getPaiesByAgent_route_actions_9b54b91c.js")
R.m(146135)
module.exports=R.m(146135).exports
